import React from 'react'
import { createRoot } from 'react-dom/client'
import App from './App.jsx'
import { LangProvider } from './i18n.jsx'
import './styles.css'
import './hero.css'
import './nav.css'
import './bg.css'
import './scene.css'
import './nav2.css'
import './nav3.css'
import './nav4.css'
import './hero2.css'
import './hero3.css'
import './about.css'
import './services.css'
import './gallery.css'
import './brands.css'
import './final.css'
import './lang.css'
createRoot(document.getElementById('root')).render(<LangProvider><App /></LangProvider>)
